[package]
name = "boa_runtime"
description = "Example runtime for the Boa JavaScript engine."
keywords = ["javascript", "js", "runtime"]
categories = ["command-line-utilities"]
version = "1.0.0-dev"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"

[dependencies]
boa_engine = { path = "../engine" }
boa_gc = { path = "../gc" }
bytemuck = "1.24.0"
either = { version = "1.15.0", optional = true }
futures = "0.3.31"
futures-lite = "2.6.1"
http = { version = "1.3.1", optional = true }
reqwest = { version = "0.12.24", optional = true }
rustc-hash = { version = "2.1.1", features = ["std"] }
serde_json = { version = "1.0.145", optional = true }
url = { version = "2.5.7", optional = true }

[dev-dependencies]
indoc = "2.0.7"
rstest = "0.26.1"
test-case = "3.3.1"
textwrap = "0.16.2"


[package.metadata.docs.rs]
all-features = true

[features]
# Default should not add `reqwest` as it is not available on all platforms.
default = ["fetch", "url"]
all = ["default", "reqwest-blocking"]
url = ["dep:url"]
fetch = [
    "dep:either",
    "dep:http",
    "dep:serde_json",
    "boa_engine/either",
]
reqwest-blocking = ["dep:reqwest", "reqwest/blocking"]
