[package]
name = "boa_string"
keywords = ["javascript", "js", "string"]
categories = ["parser-implementations", "compilers"]
readme = "../../README.md"
description = "Boa JavaScript engine component"
version = "1.0.0-dev"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"

[dependencies]
itoa = "1.0.15"
rustc-hash = { version = "2.1.1", features = ["std"] }
ryu-js = "1.0.2"

static_assertions = "1.1.0"
paste = "1.0"
fast-float2 = "0.2.3"

[features]
webassembly = []


[package.metadata.docs.rs]
all-features = true
