[package]
name = "boa_icu_provider"
description = "ICU4X data provider for the Boa JavaScript engine."
keywords = ["javascript", "cldr", "unicode"]
categories = ["internationalization", "no-std"]
version = "1.0.0-dev"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"

[dependencies]
icu_provider = { version = "2.1.1", features = ["sync"] }
icu_provider_blob = "2.1.1"
icu_provider_adapters = { version = "2.1.1", features = ["serde"] }
icu_casemap = { version = "2.1.1", features = ["serde", "datagen"] }
icu_collator = { version = "2.1.1", features = ["serde", "datagen"] }
icu_datetime = { version = "2.1.1", default-features = false, features = ["serde", "datagen"] }
icu_decimal = { version = "2.1.1", features = ["serde", "datagen"] }
icu_list = { version = "2.1.1", features = ["serde", "datagen"] }
icu_locale = { version = "2.1.1", features = ["serde", "datagen"] }
icu_normalizer = { version = "2.1.1", features = ["serde", "datagen"] }
icu_plurals = { version = "2.1.1", features = ["serde", "datagen", "experimental"] }
icu_segmenter = { version = "2.1.1", features = ["serde", "datagen"] }
once_cell = { version = "1.21.3", default-features = false, features = ["critical-section"] }
paste = "1.0"

[features]
default = ["std"]
std = ["once_cell/std"]


[package.metadata.docs.rs]
all-features = true
