[package]
name = "boa_interner"
description = "String interner for the Boa JavaScript engine."
keywords = ["javascript", "js", "string", "interner"]
categories = ["data-structures", "no-std"]
version = "1.0.0-dev"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"

[features]
serde = ["dep:serde"]
arbitrary = ["dep:arbitrary"]

[dependencies]
boa_macros = { path = "../macros" }
boa_gc = { path = "../gc" }
phf = { version = "0.13.1", default-features = false, features = ["macros"] }
rustc-hash = { version = "2.1.1", default-features = false }
static_assertions = "1.1.0"
once_cell = { version = "1.21.3", features = ["std"]}
indexmap = { version = "2.12.0", default-features = false }
serde = { version = "1.0.219", features = ["derive"], optional = true }
arbitrary = { version = "1", features = ["derive"], optional = true }
hashbrown = "0.16.0"


[package.metadata.docs.rs]
all-features = true
