[package]
name = "boa_gc"
description = "Garbage collector for the Boa JavaScript engine."
keywords = ["javascript", "js", "garbage", "memory"]
categories = ["command-line-utilities"]
version = "1.0.0-dev"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"

[features]
# Enable default implementations of trace and finalize for the thin-vec crate
thin-vec = ["dep:thin-vec"]
# Enable default implementations of trace and finalize for some `ICU4X` types
icu = ["dep:icu_locale_core"]
# Enable default implementations of trace and finalize for the `boa_string` crate
boa_string = ["dep:boa_string"]
# Enable default implementations of trace and finalize for the `either` crate
either = ["dep:either"]

[dependencies]
boa_macros = { path = "../macros" }
hashbrown = "0.16.0"

boa_string = { path = "../string", optional = true }
either = { version = "1.15.0", optional = true }
thin-vec = { version = "0.2.14", optional = true }
icu_locale_core = { version = "2.1.1", optional = true }


[package.metadata.docs.rs]
all-features = true
