[package]
name = "small_btree"
keywords = ["small", "map"]
categories = ["data-structures"]
readme = "../../README.md"
description = "Utility library that add SmallBTreeMap data structure"
version = "0.1.0"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"



[package.metadata.docs.rs]
all-features = true

[dependencies]
arrayvec = "0.7.6"
