[package]
name = "boa_parser"
description = "ECMAScript parser for the Boa JavaScript engine."
keywords = ["javascript", "js", "syntax", "parser"]
categories = ["parser-implementations", "compilers"]
version = "1.0.0-dev"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"

[dependencies]
boa_interner = { path = "../interner" }
boa_macros = { path = "../macros" }
boa_ast = { path = "../ast" }
rustc-hash = { version = "2.1.1", features = ["std"] }
fast-float2 = "0.2.3"
num-traits = "0.2.19"
bitflags = "2.10.0"
num-bigint = "0.4.6"
regress = { version = "0.10.5", features = ["utf16"] }
icu_properties = "2.1.1"

[dev-dependencies]
indoc = "2.0.7"

[features]
annex-b = []


[package.metadata.docs.rs]
all-features = true
