[package]
name = "boa_parser"
description = "ECMAScript parser for the Boa JavaScript engine."
keywords = ["javascript", "js", "syntax", "parser"]
categories = ["parser-implementations", "compilers"]
version = "1.0.0-dev"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"

[dependencies]
boa_interner.workspace = true
boa_macros.workspace = true
boa_ast.workspace = true
rustc-hash = { workspace = true, features = ["std"] }
fast-float2.workspace = true
num-traits.workspace = true
bitflags.workspace = true
num-bigint.workspace = true
regress.workspace = true
icu_properties.workspace = true

[dev-dependencies]
indoc.workspace = true
strum.workspace = true

[features]
annex-b = []


[package.metadata.docs.rs]
all-features = true
