[package]
name = "boa_ast"
description = "Abstract Syntax Tree definition for the Boa JavaScript engine."
keywords = ["javascript", "js", "syntax", "ast"]
categories = ["parser-implementations", "compilers"]
version = "1.0.0-dev"
edition = "2024"
authors = ["boa-dev"]
license = "Unlicense OR MIT"
repository = "https://github.com/boa-dev/boa"
rust-version = "1.91.0"

[features]
annex-b = []
serde = ["dep:serde", "boa_interner/serde", "bitflags/serde", "num-bigint/serde"]
arbitrary = ["dep:arbitrary", "boa_interner/arbitrary", "num-bigint/arbitrary"]

[dependencies]
boa_interner = { path = "../interner" }
boa_macros = { path = "../macros" }
boa_string = { path = "../string" }
rustc-hash = { version = "2.1.1", features = ["std"] }
bitflags = "2.10.0"
num-bigint = "0.4.6"
serde = { version = "1.0.219", features = ["derive"], optional = true }
arbitrary = { version = "1", features = ["derive"], optional = true }
indexmap = { version = "2.12.0", default-features = false }


[package.metadata.docs.rs]
all-features = true
